--========== Copyleft © 2010, Team Sandbox, Some rights reserved. ===========--
--
-- Purpose:
--
--===========================================================================--
PLAYERANIMEVENT_ATTACK_PRIMARY = 0
PLAYERANIMEVENT_ATTACK_SECONDARY = 1
PLAYERANIMEVENT_ATTACK_GRENADE = 2
PLAYERANIMEVENT_RELOAD = 3
PLAYERANIMEVENT_RELOAD_LOOP = 4
PLAYERANIMEVENT_RELOAD_END = 5
PLAYERANIMEVENT_JUMP = 6
PLAYERANIMEVENT_SWIM = 7
PLAYERANIMEVENT_DIE = 8
PLAYERANIMEVENT_FLINCH_CHEST = 9
PLAYERANIMEVENT_FLINCH_HEAD = 10
PLAYERANIMEVENT_FLINCH_LEFTARM = 11
PLAYERANIMEVENT_FLINCH_RIGHTARM = 12
PLAYERANIMEVENT_FLINCH_LEFTLEG = 13
PLAYERANIMEVENT_FLINCH_RIGHTLEG = 14
PLAYERANIMEVENT_DOUBLEJUMP = 15

-- Cancel.
PLAYERANIMEVENT_CANCEL = 16
PLAYERANIMEVENT_SPAWN = 17

-- Snap to current yaw exactly
PLAYERANIMEVENT_SNAP_YAW = 18

PLAYERANIMEVENT_CUSTOM = 19				-- Used to play specific activities
PLAYERANIMEVENT_CUSTOM_GESTURE = 20
PLAYERANIMEVENT_CUSTOM_SEQUENCE = 21	-- Used to play specific sequences
PLAYERANIMEVENT_CUSTOM_GESTURE_SEQUENCE = 22

-- TF Specific. Here until there's a derived game solution to this.
PLAYERANIMEVENT_ATTACK_PRE = 23
PLAYERANIMEVENT_ATTACK_POST = 24
PLAYERANIMEVENT_GRENADE1_DRAW = 25
PLAYERANIMEVENT_GRENADE2_DRAW = 26
PLAYERANIMEVENT_GRENADE1_THROW = 27
PLAYERANIMEVENT_GRENADE2_THROW = 28
PLAYERANIMEVENT_VOICE_COMMAND_GESTURE = 29

-- Tony; some SDK ones now too.
PLAYERANIMEVENT_STAND_TO_PRONE = 30
PLAYERANIMEVENT_CROUCH_TO_PRONE = 31
PLAYERANIMEVENT_PRONE_TO_STAND = 32
PLAYERANIMEVENT_PRONE_TO_CROUCH = 33

PLAYERANIMEVENT_COUNT = 34

-- Gesture Slots.
GESTURE_SLOT_ATTACK_AND_RELOAD = 0
GESTURE_SLOT_GRENADE = 1
GESTURE_SLOT_JUMP = 2
GESTURE_SLOT_SWIM = 3
GESTURE_SLOT_FLINCH = 4
GESTURE_SLOT_VCD = 5
GESTURE_SLOT_CUSTOM = 6

GESTURE_SLOT_COUNT = 7

GESTURE_SLOT_INVALID	= -1

function IsCustomPlayerAnimEvent( event )
	return ( event == PLAYERANIMEVENT_CUSTOM ) or ( event == PLAYERANIMEVENT_CUSTOM_GESTURE ) or
		( event == PLAYERANIMEVENT_CUSTOM_SEQUENCE ) or ( event == PLAYERANIMEVENT_CUSTOM_GESTURE_SEQUENCE );
end
